node {
   stage('Checkout') {
      checkout scm
   }
   
   stage('Build & Unit Test') {
      
   }
      
   stage('Docker_build') {
      echo "Building Docker image..."
      echo "Current directory: ${pwd}"
      sh "sudo docker build -t statelessphp:${env.BUILD_NUMBER} ./stateless-php"
   }
   
   stage('Final Testing') {
      
   }
   
   stage('Docker_push') {
      withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'docker_ub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
         sh 'echo uname=$USERNAME'
      }
   }
   
}
