node {
   stage('Checkout') {
      checkout scm
   }
   
   stage('App_build') {
      echo "Building app for Build No: ${env.BUILD_NUMBER}. (not implemented)"
   }
   
   stage('Test') {
      echo "Testing app... (not implemented)"
   }
   
   stage('Docker_build') {
      echo "Building Docker image..."
      echo "Current directory: ${pwd}"
      sh 'sudo docker build -t statelessphp:${env.BUILD_NUMBER} ./stateless-php'
   }
}
